name: Build And Upload

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run dev

      - name: Archive build
        run: tar -czf build.tar.gz build

      - name: Upload archive vis SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: build.tar.gz
          target: ~/htdocs/daria-tk-portfolio.swit.vn.ua
          strip_components: 1

      - name: Extract archive
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd htdocs/daria-tk-portfolio.swit.vn.ua
            tar -xzf build.tar.gz